/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bojan_uljarevic_calendarapp_DurationNDK */

#ifndef _Included_bojan_uljarevic_calendarapp_DurationNDK
#define _Included_bojan_uljarevic_calendarapp_DurationNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bojan_uljarevic_calendarapp_DurationNDK
 * Method:    DurationCalculate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_bojan_uljarevic_calendarapp_DurationNDK_DurationCalculate
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
